from pathlib import Path
from typing import ClassVar, Protocol, runtime_checkable


@runtime_checkable
class Platform(Protocol):
    name: ClassVar[str]

    def paste(self, method: str = "auto") -> None: ...

    def notify(self, title: str, message: str) -> None: ...

    def play_sound(self, cue: str) -> None: ...

    def open_path(self, target: str) -> None: ...

    def autostart_install(self, program: str | None = None) -> Path: ...

    def autostart_uninstall(self) -> None: ...

    def autostart_status(self) -> str: ...

    def try_lock(self, fd: int) -> bool: ...

    def unlock(self, fd: int) -> None: ...
